!$THEME = "nord"

!$color_nord0 = "#2e3440"
!$color_nord1 = "#3b4252"
!$color_nord2 = "#434c5e"
!$color_nord3 = "#4c566a"
!$color_nord4 = "#d8dee9"
!$color_nord5 = "#e5e9f0"
!$color_nord6 = "#eceff4"
!$color_nord7 = "#8fbcbb"
!$color_nord8 = "#88c0d0"
!$color_nord9 = "#81a1c1"
!$color_nord10 = "#5e81ac"
!$color_nord11 = "#bf616a"
!$color_nord12 = "#d08770"
!$color_nord13 = "#ebcb8b"
!$color_nord14 = "#a3be8c"
!$color_nord15 = "#b48ead"

skinparam {
	BackgroundColor $color_nord1
	DefaultFontColor $color_nord6
	ArrowColor $color_nord4
	ActivityBackgroundColor $color_nord2
	ActivityDiamondBackgroundColor $color_nord2
	ActorBackgroundColor $color_nord2
	AgentBackgroundColor $color_nord2
	ArchimateBackgroundColor $color_nord2
	ArtifactBackgroundColor $color_nord2
	BiddableBackgroundColor $color_nord2
	BoundaryBackgroundColor $color_nord2
	CardBackgroundColor $color_nord2
	ClassBackgroundColor $color_nord2
	ClassHeaderBackgroundColor $color_nord2
	CloudBackgroundColor $color_nord2
	CollectionsBackgroundColor $color_nord2
	ComponentBackgroundColor $color_nord2
	ControlBackgroundColor $color_nord2
	DatabaseBackgroundColor $color_nord2
	DesignedBackgroundColor $color_nord2
	DomainBackgroundColor $color_nord2
	EntityBackgroundColor $color_nord2
	EnumBackgroundColor $color_nord2
	FileBackgroundColor $color_nord2
	FolderBackgroundColor $color_nord2
	FrameBackgroundColor $color_nord2
	HexagonBackgroundColor $color_nord2
	IconPackageBackgroundColor $color_nord2
	IconPrivateBackgroundColor $color_nord2
	IconProtectedBackgroundColor $color_nord2
	IconPublicBackgroundColor $color_nord2
	InterfaceBackgroundColor $color_nord2
	LegendBackgroundColor $color_nord2
	LexicalBackgroundColor $color_nord2
	MachineBackgroundColor $color_nord2
	NodeBackgroundColor $color_nord2
	ObjectBackgroundColor $color_nord2
	PackageBackgroundColor $color_nord2
	ParticipantBackgroundColor $color_nord2
	PartitionBackgroundColor $color_nord2
	PersonBackgroundColor $color_nord2
	QueueBackgroundColor $color_nord2
	RectangleBackgroundColor $color_nord2
	RequirementBackgroundColor $color_nord2
	SequenceBoxBackgroundColor $color_nord2
	SequenceDividerBackgroundColor $color_nord2
	SequenceGroupBackgroundColor $color_nord2
	SequenceGroupBodyBackgroundColor $color_nord2
	SequenceLifeLineBackgroundColor $color_nord2
	SequenceReferenceBackgroundColor $color_nord2
	SequenceReferenceHeaderBackgroundColor $color_nord2
	StackBackgroundColor $color_nord2
	StateBackgroundColor $color_nord2
	StereotypeABackgroundColor $color_nord2
	StereotypeCBackgroundColor $color_nord2
	StereotypeEBackgroundColor $color_nord2
	StereotypeIBackgroundColor $color_nord2
	StereotypeNBackgroundColor $color_nord2
	StorageBackgroundColor $color_nord2
	SwimlaneTitleBackgroundColor $color_nord2
	TitleBackgroundColor $color_nord2
	UsecaseBackgroundColor $color_nord2

	ActivityBorderColor $color_nord6
	ActivityDiamondBorderColor $color_nord6
	ActorBorderColor $color_nord6
	AgentBorderColor $color_nord6
	ArchimateBorderColor $color_nord6
	ArtifactBorderColor $color_nord6
	BiddableBorderColor $color_nord6
	BoundaryBorderColor $color_nord6
	CardBorderColor $color_nord6
	ClassBorderColor $color_nord6
	CloudBorderColor $color_nord6
	CollectionsBorderColor $color_nord6
	ComponentBorderColor $color_nord6
	ControlBorderColor $color_nord6
	DatabaseBorderColor $color_nord6
	DesignedBorderColor $color_nord6
	'DiagramBorderColor $color_nord6
	DomainBorderColor $color_nord6
	EntityBorderColor $color_nord6
	FileBorderColor $color_nord6
	FolderBorderColor $color_nord6
	FrameBorderColor $color_nord6
	HexagonBorderColor $color_nord6
	InterfaceBorderColor $color_nord6
	LegendBorderColor $color_nord6
	LexicalBorderColor $color_nord6
	MachineBorderColor $color_nord6
	NodeBorderColor $color_nord6
	ObjectBorderColor $color_nord6
	PackageBorderColor $color_nord6
	PageBorderColor $color_nord6
	ParticipantBorderColor $color_nord6
	PartitionBorderColor $color_nord6
	PersonBorderColor $color_nord6
	QueueBorderColor $color_nord6
	RectangleBorderColor $color_nord6
	RequirementBorderColor $color_nord6
	SequenceBoxBorderColor $color_nord6
	SequenceDividerBorderColor $color_nord6
	SequenceGroupBorderColor $color_nord6
	SequenceLifeLineBorderColor $color_nord6
	SequenceReferenceBorderColor $color_nord6
	StackBorderColor $color_nord6
	StateBorderColor $color_nord6
	StereotypeABorderColor $color_nord6
	StereotypeCBorderColor $color_nord6
	StereotypeEBorderColor $color_nord6
	StereotypeIBorderColor $color_nord6
	StereotypeNBorderColor $color_nord6
	StorageBorderColor $color_nord6
	SwimlaneBorderColor $color_nord6
	TitleBorderColor $color_nord6
	UsecaseBorderColor $color_nord6
}

skinparam Note {
	BackgroundColor $color_nord8
	BorderColor $color_nord6
	FontColor $color_nord0
	StartColor $color_nord6
	EndColor $color_nord6
}

skinparam State {
	StartColor $color_nord6
	EndColor $color_nord6
}

'vim:set noexpandtab:
